### ISSUE TITLE
关于系统运行的问题

### ISSUE THREAD

**Issue by Beannn** [Accretion-dev/Accretion#1]
1.您好，对您的项目比较感兴趣，这个系统的运行环境是在Linux上面嘛，windows可以运行嘛，能**具体**一下程序在windows上运行步骤，不胜感激，期待您的回复

**Comment by Fmajor** [comment]
你好,目前项目还在开发初期. 后端还没写完,前端一点没动...
* 程序最终会是跨平台的, windos, linux 和mac都支持
* 目前我的开发环境为linux, 所以所有的开发配置脚本都是基于linux平台的

我计划首先尽快完成基本功能的开发, 然后稍微包装一下才能让windows用户正常使用
* 对于windows用户,肯定会做最大程度的封装,到时候鼠标双击一下就可以运行

预计开发时长: 半年以上(因为是个人的业余项目)
多谢关心和支持~

**Comment by Beannn** [comment]
> 你好,目前项目还在开发初期. 后端还没写完,前端一点没动...
> 
> * 程序最终会是跨平台的, windos, linux 和mac都支持
> * 目前我的开发环境为linux, 所以所有的开发配置脚本都是基于linux平台的
> 
> 我计划首先尽快完成基本功能的开发, 然后稍微包装一下才能让windows用户正常使用
> 
> * 对于windows用户,肯定会做最大程度的封装,到时候鼠标双击一下就可以运行
> 
> 预计开发时长: 半年以上(因为是个人的业余项目)
> 多谢关心和支持~
对这个我是很感兴趣的，有什么最新的信息希望发布一下，不知道您一般发布最新信息的平台是哪里呢

**Comment by Beannn** [comment]
> 你好,目前项目还在开发初期. 后端还没写完,前端一点没动...
> 
> * 程序最终会是跨平台的, windos, linux 和mac都支持
> * 目前我的开发环境为linux, 所以所有的开发配置脚本都是基于linux平台的
> 
> 我计划首先尽快完成基本功能的开发, 然后稍微包装一下才能让windows用户正常使用
> 
> * 对于windows用户,肯定会做最大程度的封装,到时候鼠标双击一下就可以运行
> 
> 预计开发时长: 半年以上(因为是个人的业余项目)
> 多谢关心和支持~

对这个我是很感兴趣的，有什么最新的信息希望发布一下，不知道您一般发布最新信息的平台是哪里呢

**Comment by Fmajor** [comment]
项目Teleram讨论群: https://t.me/accretionDevOffTopic
